### ISSUE TITLE
software license missing

### ISSUE THREAD

**Issue by erwincoumans** [trbabb/geomc#1]
At a glance you put nice effort in this library but a software license seems missing,
unless I overlooked it. Can you add a LICENSE file, preferably permissive (zlib, BSD, Apache)? Thanks for sharing!

**Comment by trbabb** [comment]
Thanks for your note! I've added an MIT license.

**Comment by trbabb** [comment]
Err, BSD, that is.

**Comment by trbabb** [comment]
- tech:
  - Collision detection in N dimensions
  - How to make a particle filter
  - Turning a kalman filter into an extended kalman filter
  - 3D rotational dynamics
  - implementing spherical harmonics
  - the vector calculus cheat sheet: derivatives and their shapes
  - what bitcoin tells us about how money works
- philosophy:
  - where right and wrong don't come from
  - the scale of consciousness, and the fallacy of Searle's "chinese room"
  - how to become correct: the asymmetry of burden of proof
  - life without the brain: what we can say about a hypothetical afterlife
  - why occam's razor is so sharp
- science:
  - the other kind of life on earth (on Blackmore's memes)
  - does the ISS cast a shadow?
  - what is random? quantum vs. "ordinary" randomness
  - quantum suicide: the anthropic principle applied to a branching universe
    (and the remote possibility that the universe has already been
    destroyed)
  - has evolution "stopped"?
  - five ways evolution can make an organism that sucks at existing
  - how could we model emotions mathematically?
  - what is CRISPr?
  - against the ubiquitous quantum mechanics "sermon"
  - the surprising history of pink bathroom slime
- life:
  - how to remember who goes first at a stop sign
  - emotional vs. intellectual communication channels
  - the four kinds of "heavy lifting" conversations that hold up a
    friendship
  - the emotion that powers society, but doesn't have a name
- other / stories:
  - my pet that ran away (it was a hive of bees)
  - infinitely aged christmas pudding
  - why saying "literally" is not as bad as everyone says
  - the spectre
